// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ZM1DhLizMvysCtLcnPS9pd4YsoBgkrc',
    appId: '1:887738727955:web:784cd25f56ebc725b389e6',
    messagingSenderId: '887738727955',
    projectId: 'noti-229b1',
    authDomain: 'noti-229b1.firebaseapp.com',
    storageBucket: 'noti-229b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2HE9hzawSeMldn91gnPJWfKt_uZ8vsQ',
    appId: '1:887738727955:android:9467a1c559fcb20bb389e6',
    messagingSenderId: '887738727955',
    projectId: 'noti-229b1',
    storageBucket: 'noti-229b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAIz0MBMR2epugPTt5VbIWpUdJVZwmQM',
    appId: '1:887738727955:ios:72e20351d459e89ab389e6',
    messagingSenderId: '887738727955',
    projectId: 'noti-229b1',
    storageBucket: 'noti-229b1.appspot.com',
    iosBundleId: 'com.example.plp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtAIz0MBMR2epugPTt5VbIWpUdJVZwmQM',
    appId: '1:887738727955:ios:0924858ab7f81115b389e6',
    messagingSenderId: '887738727955',
    projectId: 'noti-229b1',
    storageBucket: 'noti-229b1.appspot.com',
    iosBundleId: 'com.example.plp.RunnerTests',
  );
}
